artikel/urls.py
from django.urls import path
from artikel.views import show_artikel, show_artikel_detail, add, show_json, show_json_flutter
app_name = 'artikel'

urlpatterns = [
    path('', show_artikel, name='show_artikel'),
    path('<int:pk>', show_artikel_detail, name='detail'),
    path('add/', add, name='add'),
    path('show_json', show_json, name='show_json'),
    path('show_json_flutter', show_json_flutter, name='show_json_flutter')

]

autentikasi/urls.py
from django.urls import path
from autentikasi.views import login_user, logout_user, register, loginFlutter, registerFlutter, logoutFlutter

app_name = 'autentikasi'

urlpatterns = [
    path('register/', register, name='register'),
    path('', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('login_apk/', loginFlutter, name='login_apk'),
    path('reg_apk/', registerFlutter, name='reg_apk'),
    path('logout_apk/', logoutFlutter, name='logout_apk'),
]

homepage/urls.py
from django.urls import path
from homepage.views import home, list_pertanyaan
from homepage.views import show_json
from homepage.views import faq_ajax
from homepage.views import list_pertanyaan
from homepage.views import faq_flutter

app_name = 'homepage'

urlpatterns = [
    path('', home, name='homepage'),
    path('json/', show_json, name='show_json'),
    path('home/', home, name='home'),
    path('faq_ajax/', faq_ajax, name='faq_ajax'),
    path('list_pertanyaan/', list_pertanyaan, name='list_pertanyaan'),
    path('faq_flutter/', faq_flutter, name='faq_flutter'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('autentikasi/', include('autentikasi.urls')),
    path('notification/', include('notification.urls')),
    path('profile/', include('userprofile.urls')),
    path('artikel/', include('artikel.urls')),
    path('crowdfund/', include('crowdfund.urls'))
]

# TODO: Implement Routings Here

artikel/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Artikel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add = True)
    title = models.TextField()
    short_description = models.TextField(max_length=60)
    description = models.TextField()
    class Meta:
        ordering = ['-date']

artikel/views.py
from django.shortcuts import render
from math import trunc
from .models import Artikel
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
def show_artikel(request):
    list_artikel = Artikel.objects.all()
    date = datetime.today()
    context = {
    'list_artikel': list_artikel,
    'date':date,
    }
    return render(request, "artikel.html", context)

def show_artikel_detail(request, pk):
    data = Artikel.objects.filter(pk=pk)
    context = {
        'artikel':data,
        }
    return render(request, "artikel_detail.html", context)

def show_json(request):

    artikel = Artikel.objects.all()
    users = User.objects.all()
    seconds_in_day = 60 * 60 * 24
    print(" ===== ==== == = = === \n")
    time_diff = {}
    for art in artikel.values():
        total_seconds = (datetime.today().replace(tzinfo=None) -  (art["date"].replace(tzinfo=None))).total_seconds()
        day = trunc(total_seconds / seconds_in_day )
        hour = trunc((total_seconds - (day*seconds_in_day))/3600)
        minute = trunc((total_seconds - day*seconds_in_day - hour*3600)/60)
        second = trunc(total_seconds - day*seconds_in_day - hour*3600 - minute*60)
        if (day == 0):
            if (hour == 0):
                if (minute == 0):
                    diff = str(second) + " seconds ago"
                elif (minute == 1):
                    diff = str(minute) + " minute ago"
                else:
                    diff = str(minute) + " minutes ago"
            elif (hour == 1):
                diff = str(hour) + " hour ago"
            else:
                diff = str(hour) + " hours ago"
        elif (day == 1):
            diff = str(day) + " day ago"
        else:
            diff = str(day) + " days ago"
        time_diff[art["id"]] = diff
    return JsonResponse({"artikel":list(artikel.values()), "user":list(users.values('username', 'pk')), "time_diff":time_diff},)

def show_json_flutter(request):
    artikel = Artikel.objects.all()
    seconds_in_day = 60 * 60 * 24
    print(" ===== ==== == = = === \n")
    print(artikel.values())
    result = []
    for art in artikel.values():
        temp = art
        temp["author"] = str(User.objects.filter(pk=art["user_id"])[0])
        total_seconds = (datetime.today().replace(tzinfo=None) -  (art["date"].replace(tzinfo=None))).total_seconds()
        day = trunc(total_seconds / seconds_in_day )
        hour = trunc((total_seconds - (day*seconds_in_day))/3600)
        minute = trunc((total_seconds - day*seconds_in_day - hour*3600)/60)
        second = trunc(total_seconds - day*seconds_in_day - hour*3600 - minute*60)
        if (day == 0):
            if (hour == 0):
                if (minute == 0):
                    diff = str(second) + " seconds ago"
                elif (minute == 1):
                    diff = str(minute) + " minute ago"
                else:
                    diff = str(minute) + " minutes ago"
            elif (hour == 1):
                diff = str(hour) + " hour ago"
            else:
                diff = str(hour) + " hours ago"
        elif (day == 1):
            diff = str(day) + " day ago"
        else:
            diff = str(day) + " days ago"
        temp["time_diff"] = str(diff)
        result.append(temp)
    return JsonResponse(result, safe=False)

@csrf_exempt
def add(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = str(request.POST.get('description'))

        artikel = Artikel(user=request.user, title=title, description=description, date=datetime.today(), short_description=str(description)[0:60])
        artikel.save()
        return JsonResponse(
            {
            "pk": artikel.pk,
            "user": str(request.user),
            "title": title,
            "date": datetime.today(),
            "short_description": str(description)[0:60],
        }, status=200)

artikel/templates/artikel.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Artikel</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

{% endblock meta %}

{% block content %}


<div class="">

  <div class="my-5 py-5">
    
    <div class="button_container">
      <h1 class="d-flex justify-content-center mt-3 button_container">Artikel</h1>
      <div class="d-flex justify-content-center mt-3 button_container">
        {% if user.is_authenticated %} 
          <button font-family: 'poppins'; background-color: #ffffff;" type="button" class="submit mt-0 ml-1 px-2 p-3"  data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">
          Buat Artikel Baru</button>
          <a href="{% url 'homepage:homepage' %}"><button font-family: 'poppins'; background-color: #ffffff;" type="button" class="submit mt-0 ml-1 px-2 p-3">Kembali </button></a>
        {% else %}
        <a href="{% url 'autentikasi:login' %}">login </a>  untuk menambah artikel
        <a href="{% url 'homepage:homepage' %}"><button font-family: 'poppins'; background-color: #ffffff;" type="button" class="submit mt-0 ml-1 px-2 p-3">Kembali </button></a>
        {% endif %} 
      </div>
    </div>
<br>

<!--cards start here-->
<div id = "artikel_containers" class="list-group mx-auto my-0" style="width: 40%;" >

</div>

<br/>
<br/>
<br/>
</div>
<!--end-->
</div>
</div>
<!--modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Buat Artikel Baru</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="form_artikel">
              {% csrf_token%}
            <div class="mb-3">
              <label for="title" class="col-form-label">Judul:</label>
              <input type="text" class="form-control" id="title">
            </div>
            <div class="mb-3">
              <label for="description" class="col-form-label">Deskripsi:</label>
              <textarea class="form-control" id="description"></textarea>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" value="submit" class="btn btn-primary" id="submit_btn">Create</button>
            </div>
          </form>
        </div>
  
      </div>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  
  <script src="{% static 'js/artikel.js'%}"></script>
{% endblock content %}

artikel/templates/artikel_detail.html
{% extends 'base.html' %}

{% block meta %}
<title>Artikel</title>
<style>
      .footer {
  position: fixed;
  bottom: auto;
  }

  .logo {
      width: 50px;
      height: 20px;
      object-fit: cover;
    }
</style>
{% endblock meta %}

{% block content %}
<div class="">

    <div class="my-5 py-5">
{% for data in artikel %}
<h1>{{data.title}}</h1>
<h2> by {{data.user}} on {{data.date}}</h2>
<p>{{data.description}}</p>
</div>
</div>
{% endfor %}
{% endblock content %}