artikel/urls.py
from django.urls import path
from artikel.views import show_artikel, show_artikel_detail, add, show_json, show_json_flutter
app_name = 'artikel'

urlpatterns = [
    path('', show_artikel, name='show_artikel'),
    path('<int:pk>', show_artikel_detail, name='detail'),
    path('add/', add, name='add'),
    path('show_json', show_json, name='show_json'),
    path('show_json_flutter', show_json_flutter, name='show_json_flutter')

]

notification/urls.py
from django.urls import path
from .views import *

app_name = "notification"

urlpatterns = [
    path('', show_notification, name='show_notification'),
    path('json/', notification_json, name='notification_json'),
    path('ajax-tambah-saldo', ajax_tambah_saldo, name='ajax-tambah-saldo'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('autentikasi/', include('autentikasi.urls')),
    path('notification/', include('notification.urls')),
    path('profile/', include('userprofile.urls')),
    path('artikel/', include('artikel.urls')),
    path('crowdfund/', include('crowdfund.urls'))
]

# TODO: Implement Routings Here

userprofile/urls.py
from django.urls import path
from userprofile.views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'userprofile'

urlpatterns = [
    path('', show_profile, name='show_profile'),
    path('edit', edit_profile, name='edit_profile'),
    path('edit-profile-flutter', edit_profile_flutter, name='edit_profile_flutter'),
    path('json', show_json, name='show_json'),
    path('saldo', edit_saldo, name='edit_saldo'),
    path('topup', show_topup, name='show_topup'),
    path('json-flutter', show_json_flutter, name='show_json_flutter'),
    path('saldo-flutter', edit_saldo_flutter, name='edit_saldo_flutter')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import math


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    time = models.DateTimeField(null=True, blank=True)
    timesince = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return f"({self.pk}) {self.title} | {self.user.username}"

    def whenpublished(self):
        now = timezone.now()
        
        diff= now - self.time

        if diff.days == 0 and diff.seconds >= 0 and diff.seconds < 60:
            seconds= diff.seconds
            
            if seconds == 1:
                self.timesince = str(seconds) +  "second ago"
            
            else:
                self.timesince = str(seconds) + " seconds ago"

            

        if diff.days == 0 and diff.seconds >= 60 and diff.seconds < 3600:
            minutes= math.floor(diff.seconds/60)

            if minutes == 1:
                self.timesince = str(minutes) + " minute ago"
            
            else:
                self.timesince = str(minutes) + " minutes ago"



        if diff.days == 0 and diff.seconds >= 3600 and diff.seconds < 86400:
            hours= math.floor(diff.seconds/3600)

            if hours == 1:
                self.timesince = str(hours) + " hour ago"

            else:
                self.timesince = str(hours) + " hours ago"

        # 1 day to 30 days
        if diff.days >= 1 and diff.days < 30:
            days= diff.days
        
            if days == 1:
                self.timesince = str(days) + " day ago"

            else:
                self.timesince = str(days) + " days ago"

        if diff.days >= 30 and diff.days < 365:
            months= math.floor(diff.days/30)
            

            if months == 1:
                self.timesince = str(months) + " month ago"

            else:
                self.timesince = str(months) + " months ago"


        if diff.days >= 365:
            years= math.floor(diff.days/365)

            if years == 1:
                self.timesince = str(years) + " year ago"

            else:
                self.timesince = str(years) + " years ago"

notification/forms.py
from django.forms import ModelForm
from userprofile.models import UserProfile
from .models import Notification

class NotificationForms(ModelForm):
    class Meta:
        model = Notification
        fields = '__all__'

class SaldoForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['saldo']

notification/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseBadRequest
from django.core import serializers
from django.contrib.auth.decorators import login_required
from userprofile.models import UserProfile
from django.views.decorators.csrf import csrf_exempt
from django.http.request import QueryDict
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User


from .models import Notification
from .forms import SaldoForm

@login_required(login_url="/autentikasi/")
def show_notification(request):
    return render(request, "notification.html")

@login_required(login_url="/autentikasi/")
def notification_json(request):
    user = request.user
    data = Notification.objects.filter(user=user)
    for instance in data:
        instance.whenpublished()
        instance.save()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def ajax_tambah_saldo(request):
    user = request.user.userprofile

    if request.method=="PATCH":
        data = QueryDict(request.body)
        new_saldo = user.saldo + int(data["saldo"])
        form = SaldoForm(data={'saldo': new_saldo}, instance=user)

        if form.is_valid():
            form.save()
            return HttpResponse(b"UPDATED", status=201)

    return HttpResponseBadRequest("PATCH method required")

notification/templates/notification.html
{% extends 'base.html' %}

{% block content %}
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<style>
  .submit{
  display: inline-block !important;
  padding: 5px 10px !important;
  color: rgb(162, 123, 92) !important;
  border: 1px solid rgb(162, 123, 92) !important;
  border-radius: 23px;
  font-weight: 500 !important;
  letter-spacing: 0.3px !important;
  transition: all 0.5s;
  }

  .footer {
  position: fixed;
  bottom: auto;
  }

  .logo {
      width: 50px;
      height: 20px;
      object-fit: cover;
    }
</style>

<div class="">
  
    <div class="my-5 py-5">
      <div class="list-group mx-auto my-0" style="width: 40%;">
        <a href="#" class="list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-between">
            <h3 class="mb-0">Notifikasi</h3>
            <!-- Button trigger modal -->
            <button type="button" class="submit" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Tambah Saldo
            </button>
          </div>
        </a>
      </div>
      <div class="notifications mb-5"></div>
      <br/>
      <br/>
      <br/>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Tambahkan Saldo</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form id="form" method="PATCH">
              {% csrf_token %}
            <div class="row">
              <div class="col-12">
                <div class="d-flex flex-column px-md-5 px-4 mb-4">
                  <span>Credit Card</span>
                  <div class="inputWithIcon">
                    <input
                      class="form-control"
                      type="text"
                      value="5136 1845 5468 3894"
                    />
                    <span>
                      <img
                        class='logo'
                        src="https://www.freepnglogos.com/uploads/mastercard-png/mastercard-logo-logok-15.png"
                        alt=""
                    /></span>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="d-flex flex-column ps-md-5 px-md-0 px-4 mb-4">
                  <span>Expiration<span class="ps-1">Date</span></span>
                  <div class="inputWithIcon">
                    <input type="text" class="form-control" value="05/20" />
                    <span class="fas fa-calendar-alt"></span>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="d-flex flex-column pe-md-5 px-md-0 px-4 mb-4">
                  <span>Code CVV</span>
                  <div class="inputWithIcon">
                    <input type="password" class="form-control" value="123" />
                    <span class="fas fa-lock"></span>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div class="d-flex flex-column px-md-5 px-4 mb-4">
                  <span>Name</span>
                  <div class="inputWithIcon">
                    <input
                      class="form-control text-uppercase"
                      type="text"
                      value="valdimir berezovkiy"
                    />
                    <span class="far fa-user"></span>
                  </div>
                </div>
              </div>
              <div class="col-12">
                  <div class="d-flex flex-column px-md-5 px-4 mb-0">
                    <span>Amount</span>
                    <div class="inputWithIcon">
                      <input
                        class="form-control text-uppercase"
                        type="text"
                        value="10000"
                        id="saldo"
                        name="saldo"
                      />
                      <span class="far fa-user"></span>
                    </div>
                    <p id="currentSaldo" class="mt-2">Saldo saat ini: Rp. </p>
                  </div>
                </div>
              <div class="col-12 px-md-5 px-4 mt-0">
                <button id="tambahSaldoBtn" type="button" class="btn btn-primary w-100" type="submit" data-bs-dismiss="modal">Top Up</div>
              </div>
            </div>
          </form>
          </div>
        </div>
      </div>
</div>

</div>

<script>
    
    $(document).ready(function() {
      load();
    });
  
    async function load() {
      // Get daftar notifikasi
      $.ajax({url: "{% url 'notification:notification_json' %}", type: 'GET', success: function(data) {
        var res = ``;
        for (i = 0; i<data.length; i++) {
          res+=
          
                `
                <a href="#" class="list-group-item list-group-item-action mx-auto my-0" style="width: 40%;">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">${data[i].fields.title}</h5>
                    <small class="text-muted">${data[i].fields.timesince}</small>
                  </div>
                  <p class="mb-1">${data[i].fields.description}</p>
                </a>
                `
        }
        $(".notifications").html(res+"</div>");
      }});

      // Get saldo user
      $.ajax({url: "{% url 'userprofile:show_json' %}", type: 'GET', success: function(data) {
        $("#currentSaldo").html("Saldo saat ini: Rp. " + data[0].fields.saldo);
      }});

    };
    
    $("#tambahSaldoBtn").click(function() {
    var data = $("#form");
    $.ajax({
      type:'PATCH',
      url: "{% url 'notification:ajax-tambah-saldo' %}",
      data: data.serialize(),
      success: function() {
          $("#form")[0].reset();
          load();
      }
    });
  });

  </script>

{% endblock content %}