artikel/urls.py
from django.urls import path
from artikel.views import show_artikel, show_artikel_detail, add, show_json, show_json_flutter
app_name = 'artikel'

urlpatterns = [
    path('', show_artikel, name='show_artikel'),
    path('<int:pk>', show_artikel_detail, name='detail'),
    path('add/', add, name='add'),
    path('show_json', show_json, name='show_json'),
    path('show_json_flutter', show_json_flutter, name='show_json_flutter')

]

crowdfund/urls.py
from .views import *
from django.urls import path

app_name = "crowdfund"

urlpatterns = [
    path("", show_crowdfunds, name="show_crowdfunds"),
    path("<int:id>/", show_crowdfund, name="show_crowdfund"),
    path("funds/json/ongoing/", show_crowdfunds_json_ongoing, name="show_crowdfunds_json_ongoing"),
    path("funds/json/myfunds/", show_crowdfunds_json_by_me, name="show_crowdfunds_json_by_me"),
    path("funds/json/<int:id>/", show_crowdfund_json, name="show_crowdfund_json"),
    path("donations/json/<int:id>/", show_donations_json_by_fund, name="show_donations_json_by_fund"),
    path("funds/add/", add_crowdfund, name="add_crowdfund"),
    path("donations/add/<int:id>/", add_donation, name="add_donation"),
    path("flutter/funds/<str:fundraiser_name>/", flutter_crowdfunds_by_fundraiser, name="flutter_crowdfunds_by_fundraiser"),
    path("flutter/funds/add/", flutter_add_crowdfund, name="flutter_add_crowdfund"),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('autentikasi/', include('autentikasi.urls')),
    path('notification/', include('notification.urls')),
    path('profile/', include('userprofile.urls')),
    path('artikel/', include('artikel.urls')),
    path('crowdfund/', include('crowdfund.urls'))
]

# TODO: Implement Routings Here

crowdfund/models.py
from django.db import models
from userprofile.models import UserProfile

class Crowdfund(models.Model):
    fundraiser = models.ForeignKey(UserProfile, on_delete = models.CASCADE, blank=True, null=True)
    fundraiser_name = models.CharField(max_length=150, blank=True, null=True)
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    collected = models.PositiveIntegerField()
    target = models.PositiveIntegerField()
    deadline = models.DateTimeField()

class Donation(models.Model):
    donator = models.ForeignKey(UserProfile, on_delete = models.CASCADE, blank=True, null=True)
    donator_name = models.CharField(max_length=150, blank=True, null=True)
    crowdfund = models.ForeignKey(Crowdfund, on_delete = models.CASCADE)
    amount = models.PositiveIntegerField()
    comment = models.TextField(blank=True)

crowdfund/forms.py
from .models import Crowdfund, Donation
from datetime import datetime
from django.forms import ModelForm
from pytz import timezone

class CrowdfundForm(ModelForm):
    class Meta:
        model = Crowdfund
        fields = ["title", "description", "target", "deadline"]

    def clean(self):
        cleaned = super().clean()
        title = cleaned.get("title")
        description = cleaned.get("description")
        target = cleaned.get("target")
        deadline = cleaned.get("deadline")
        if (title != None) and (description != None) and (target != None) and (deadline != None):
            if len(title) < 1 or len(title) > 50:
                self.add_error("title", "Judul harus di antara 1 dan 50 karakter.")
            if len(description) > 1000:
                self.add_error("description", "Deskripsi harus tidak lebih dari 1000 karakter.")
            if target < 1 or target > 1000000000:
                self.add_error("target", "Target dana harus di antara 1 dan 1000000000.")
            if deadline < datetime.now().replace(tzinfo=timezone("UTC")):
                self.add_error("deadline", "Batas waktu harus tidak kurang dari saat ini.")

class DonationForm(ModelForm):
    class Meta:
        model = Donation
        fields = ["amount", "comment"]

    def clean(self):
        cleaned = super().clean()
        amount = cleaned.get("amount")
        comment = cleaned.get("comment")
        if (amount != None) and (comment != None):
            if amount < 1 or amount > 1000000000:
                self.add_error("amount", "Jumlah donasi harus di antara 1 dan jumlah saldo.")
            if len(comment) > 1000:
                self.add_error("comment", "Komentar harus tidak lebih dari 1000 karakter.")

crowdfund/views.py
from .forms import CrowdfundForm, DonationForm
from .models import Crowdfund, Donation
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import serializers
from django.db.models import F
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from notification.models import Notification
from pytz import timezone
import json

def show_crowdfunds(request):
    context = {
        "logged_in": request.user.is_authenticated,
        "user": request.user,
        "role": getattr(getattr(request.user, "userprofile", None), "role", None)
        }
    if context["role"] == "Fundraiser":
        return render(request, "crowdfunds_fundraiser.html", context)
    return render(request, "crowdfunds_donator.html", context)

@login_required(login_url="/autentikasi/")
def show_crowdfund(request, id):
    context = {
        "id": id,
        "role": request.user.userprofile.role
        }
    if context["role"] == "Fundraiser":
        return render(request, "crowdfund_fundraiser.html", context)
    return render(request, "crowdfund_donator.html", context)

def show_crowdfunds_json_ongoing(request):
    crowdfunds = Crowdfund.objects\
        .filter(deadline__gt=datetime.now().replace(tzinfo=timezone("UTC")))\
        .filter(collected__lt=F("target"))
    return HttpResponse(serializers.serialize("json", crowdfunds), content_type="application/json")

@login_required(login_url="/autentikasi/")
def show_crowdfunds_json_by_me(request):
    crowdfunds = Crowdfund.objects.filter(fundraiser__user=request.user)
    return HttpResponse(serializers.serialize("json", crowdfunds), content_type="application/json")

@login_required(login_url="/autentikasi/")
def show_crowdfund_json(request, id):
    crowdfund = Crowdfund.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", crowdfund), content_type="application/json")

@login_required(login_url="/autentikasi/")
def show_donations_json_by_fund(request, id):
    donations = Donation.objects.filter(crowdfund__pk=id)
    return HttpResponse(serializers.serialize("json", donations), content_type="application/json")

@login_required(login_url="/autentikasi/")
def add_crowdfund(request):
    form = CrowdfundForm(request.POST)
    form.instance.fundraiser = request.user.userprofile
    form.instance.fundraiser_name = request.user.username
    form.instance.collected = 0
    if form.is_valid():
        form.save()
        crowdfund = [Crowdfund.objects.all().last()]
        return HttpResponse(serializers.serialize("json", crowdfund), content_type="application/json")
    return JsonResponse({"error": True})

@login_required(login_url="/autentikasi/")
def add_donation(request, id):
    form = DonationForm(request.POST)
    form.instance.donator = request.user.userprofile
    form.instance.donator_name = request.user.username
    form.instance.crowdfund = Crowdfund.objects.get(pk=id)
    if form.is_valid() and form.instance.donator.saldo > form.instance.amount:
        form.save()
        form.instance.donator.saldo -= form.instance.amount
        form.instance.donator.save()
        form.instance.crowdfund.fundraiser.saldo += form.instance.amount
        form.instance.crowdfund.fundraiser.save()
        form.instance.crowdfund.collected += form.instance.amount
        form.instance.crowdfund.save()
        fundraiser_notif = Notification.objects.create(
            user=form.instance.crowdfund.fundraiser.user,
            title=f"Anda menerima donasi sebesar {form.instance.amount}",
            description=f"{form.instance.donator_name} memberikan donasi untuk penggalangan dana {form.instance.crowdfund.title}.",
            time=datetime.now(timezone('Asia/Jakarta'))
        )
        fundraiser_notif.save()
        donatur_notif = Notification.objects.create(
            user=request.user,
            title=f"Anda memberikan donasi sebesar {form.instance.amount}",
            description=f"Donasi diberikan kepada {form.instance.crowdfund.fundraiser_name} untuk penggalangan dana {form.instance.crowdfund.title}.",
            time=datetime.now(timezone('Asia/Jakarta'))
        )
        donatur_notif.save()
        donation = [form.instance.crowdfund]
        return HttpResponse(serializers.serialize("json", donation), content_type="application/json")
    return JsonResponse({"error": True})

def flutter_crowdfunds_by_fundraiser(request, fundraiser_name):
    crowdfunds = Crowdfund.objects.filter(fundraiser_name=fundraiser_name)
    return HttpResponse(serializers.serialize("json", crowdfunds), content_type="application/json")

@csrf_exempt
def flutter_add_crowdfund(request):
    data = json.loads(request.body)
    form = Crowdfund.objects.create(
        fundraiser=User.objects.get(username=form.instance.fundraiser_name),
        fundraiser_name=data["fundraiser_name"],
        title=data["title"],
        description=data["description"],
        collected=0,
        target=data["target"],
        deadline=data["deadline"],
    )
    form.save()
    return JsonResponse({"status": "success"})

crowdfund/templates/crowdfund.html
{% extends 'base.html' %}

{% block meta %}
  <script src="{% static 'crowdfund.js' %}"></script>
{% endblock meta %}

{% block content %}
  <div class="modal fade" id="form" data-bs-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Formulir Donasi</h5>
          <a class="btn-close" data-bs-dismiss="modal"></a>
        </div>
        <div class="modal-body text-center">
          <form method="POST" action="">
            {% csrf_token %}
            <h6>Jumlah Donasi</h6>
            <input type="number" id="amount" placeholder="0" class="form-control">
            <br>
            <h6>Komentar kepada Penggalang Dana</h6>
            <input type="text" id="comment" placeholder="Tuliskan komentarmu di sini" class="form-control">
            <br>
            <input class="btn border" type="submit" value="Kumpulkan">
          </form>
        </div>
      </div>
    </div>
  </div>
  
  <div class="modal fade" id="history" data-bs-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Riwayat Donasi</h5>
          <a class="btn-close" data-bs-dismiss="modal"></a>
        </div>
        <div class="modal-body text-center" id="donations"></div>
      </div>
    </div>
  </div>
{% endblock content %}

crowdfund/templates/crowdfund_donator.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <script>
      var crowdfundUrl = "{% url 'crowdfund:show_crowdfund_json' id %}"
      var addDonationUrl = "{% url 'crowdfund:add_donation' id %}"
  </script>
  <script src="{% static 'crowdfund_donator.js' %}"></script>
{% endblock meta %}

{% block content %}
  <div class="my-5 py-5" id="crowdfund">
    <div class="row justify-content-center p-3" id="detail"></div>
  </div>
  <div class="modal fade" id="form">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Formulir Donasi</h5>
          <button type="button" class="close" data-bs-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body text-center">
          <form method="POST" action="">
            {% csrf_token %}
            <h6>Jumlah Donasi</h6>
            <span class="text-muted">Jumlah donasi harus di antara 1 dan jumlah saldo.</span>
            <input type="number" id="amount" placeholder="0" class="form-control">
            <br>
            <h6>Komentar kepada Penggalang Dana</h6>
            <span class="text-muted">Komentar harus tidak lebih dari 1000 karakter.</span>
            <input type="text" id="comment" placeholder="Tuliskan komentarmu di sini" class="form-control">
            <br>
            <div class="text-danger" id="error"></div>
            <input class="btn border" type="submit" value="Kumpulkan">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

crowdfund/templates/crowdfund_fundraiser.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <script>
      var crowdfundUrl = "{% url 'crowdfund:show_crowdfund_json' id %}"
      var donationUrl = "{% url 'crowdfund:show_donations_json_by_fund' id %}"
  </script>
  <script src="{% static 'crowdfund_fundraiser.js' %}"></script>
{% endblock meta %}

{% block content %}
  <div class="my-5 py-5" id="crowdfund">
    <div class="row justify-content-center p-3" id="detail"></div>
  </div>
  <div class="modal fade" id="history">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Riwayat Donasi</h5>
          <button type="button" class="close" data-bs-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body text-center" id="donations">
          <p class="text-muted" id="no-donations">Belum ada donasi yang terkumpul.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

crowdfund/templates/crowdfunds_donator.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Daftar Penggalangan Dana</title>
  <script>
    var crowdfundUrl = "{% url 'crowdfund:show_crowdfund' 1 %}"
    var ongoingUrl = "{% url 'crowdfund:show_crowdfunds_json_ongoing' %}"
  </script>
  <script src="{% static 'crowdfunds_donator.js' %}"></script>
{% endblock meta %}

{% block content %}
  <div class="text-center p-3 my-5 py-5">
    <h1>Daftar Penggalangan Dana</h1>
    {% if not logged_in  %}
      <h5 class="text-muted">Login untuk melihat detail dan berdonasi kepada orang-orang yang membutuhkan</h3>
    {% else %}
      <h5 class="text-muted">Ayo berdonasi kepada orang-orang yang membutuhkan, {{user}}</h3>
    {% endif %}
    <div class="text-muted" id="no-crowdfunds">
      <br><br>
      Belum ada galangan dana yang sedang berlangsung saat ini.
    </div>
    <div class="row justify-content-center p-3" id="crowdfunds"></div>
  </div>
{% endblock content %}

crowdfund/templates/crowdfunds_fundraiser.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Daftar Penggalangan Dana</title>
  <script>
    var crowdfundUrl = "{% url 'crowdfund:show_crowdfund' 1 %}"
    var myFundsUrl = "{% url 'crowdfund:show_crowdfunds_json_by_me' %}"
    var addFundUrl = "{% url 'crowdfund:add_crowdfund' %}"
  </script>
  <script src="{% static 'crowdfunds_fundraiser.js' %}"></script>
{% endblock meta %}

{% block content %}
  <div class="text-center p-3 my-5 py-5">
    <h1>Daftar Penggalangan Dana</h1>
    <h5 class="text-muted">Berikut adalah galangan dana yang Anda ajukan, {{user}}</h3>
    <br>
    <a class="btn border" data-bs-toggle="modal" data-bs-target="#form">Galang Dana Baru</a>
    <div class="text-muted" id="no-crowdfunds">
      <br><br>
      Anda belum mengajukan penggalangan dana.
    </div>
    <div class="row justify-content-center p-3" id="crowdfunds"></div>
  </div>

  <div class="modal fade" id="form">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Formulir Penggalangan Dana</h5>
          <button type="button" class="close" data-bs-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body text-center">
          <form method="POST" action="">
            {% csrf_token %}
            <h6>Judul Penggalangan Dana</h6>
            <span class="text-muted">Judul harus di antara 1 dan 50 karakter.</span>
            <input type="text" id="title" placeholder="Masukkan judul di sini" class="form-control" required>
            <br>
            <h6>Informasi mengenai Penggalangan Dana</h6>
            <span class="text-muted">Deskripsi harus tidak lebih dari 1000 karakter.</span>
            <input type="text" id="description" placeholder="Masukkan deskripsi di sini" class="form-control">
            <br>
            <h6>Target Dana Terkumpul</h6>
            <span class="text-muted">Target dana harus di antara 1 dan 1000000000.</span>
            <input type="number" id="target" placeholder="0" class="form-control" required>
            <br>
            <h6>Batas Waktu Pengumpulan Dana</h6>
            <span class="text-muted">Batas waktu harus tidak kurang dari saat ini.</span>
            <input type="datetime-local" id="deadline" class="form-control" required>
            <br>
            <div class="text-danger" id="error"></div>
            <input class="btn border" type="submit" value="Galang Dana">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}