artikel/urls.py
from django.urls import path
from artikel.views import show_artikel, show_artikel_detail, add, show_json, show_json_flutter
app_name = 'artikel'

urlpatterns = [
    path('', show_artikel, name='show_artikel'),
    path('<int:pk>', show_artikel_detail, name='detail'),
    path('add/', add, name='add'),
    path('show_json', show_json, name='show_json'),
    path('show_json_flutter', show_json_flutter, name='show_json_flutter')

]

autentikasi/urls.py
from django.urls import path
from autentikasi.views import login_user, logout_user, register, loginFlutter, registerFlutter, logoutFlutter

app_name = 'autentikasi'

urlpatterns = [
    path('register/', register, name='register'),
    path('', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('login_apk/', loginFlutter, name='login_apk'),
    path('reg_apk/', registerFlutter, name='reg_apk'),
    path('logout_apk/', logoutFlutter, name='logout_apk'),
]

crowdfund/urls.py
from .views import *
from django.urls import path

app_name = "crowdfund"

urlpatterns = [
    path("", show_crowdfunds, name="show_crowdfunds"),
    path("<int:id>/", show_crowdfund, name="show_crowdfund"),
    path("funds/json/ongoing/", show_crowdfunds_json_ongoing, name="show_crowdfunds_json_ongoing"),
    path("funds/json/myfunds/", show_crowdfunds_json_by_me, name="show_crowdfunds_json_by_me"),
    path("funds/json/<int:id>/", show_crowdfund_json, name="show_crowdfund_json"),
    path("donations/json/<int:id>/", show_donations_json_by_fund, name="show_donations_json_by_fund"),
    path("funds/add/", add_crowdfund, name="add_crowdfund"),
    path("donations/add/<int:id>/", add_donation, name="add_donation"),
    path("flutter/funds/<str:fundraiser_name>/", flutter_crowdfunds_by_fundraiser, name="flutter_crowdfunds_by_fundraiser"),
    path("flutter/funds/add/", flutter_add_crowdfund, name="flutter_add_crowdfund"),
]

homepage/urls.py
from django.urls import path
from homepage.views import home, list_pertanyaan
from homepage.views import show_json
from homepage.views import faq_ajax
from homepage.views import list_pertanyaan
from homepage.views import faq_flutter

app_name = 'homepage'

urlpatterns = [
    path('', home, name='homepage'),
    path('json/', show_json, name='show_json'),
    path('home/', home, name='home'),
    path('faq_ajax/', faq_ajax, name='faq_ajax'),
    path('list_pertanyaan/', list_pertanyaan, name='list_pertanyaan'),
    path('faq_flutter/', faq_flutter, name='faq_flutter'),
]

notification/urls.py
from django.urls import path
from .views import *

app_name = "notification"

urlpatterns = [
    path('', show_notification, name='show_notification'),
    path('json/', notification_json, name='notification_json'),
    path('ajax-tambah-saldo', ajax_tambah_saldo, name='ajax-tambah-saldo'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('autentikasi/', include('autentikasi.urls')),
    path('notification/', include('notification.urls')),
    path('profile/', include('userprofile.urls')),
    path('artikel/', include('artikel.urls')),
    path('crowdfund/', include('crowdfund.urls'))
]

# TODO: Implement Routings Here

userprofile/urls.py
from django.urls import path
from userprofile.views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'userprofile'

urlpatterns = [
    path('', show_profile, name='show_profile'),
    path('edit', edit_profile, name='edit_profile'),
    path('edit-profile-flutter', edit_profile_flutter, name='edit_profile_flutter'),
    path('json', show_json, name='show_json'),
    path('saldo', edit_saldo, name='edit_saldo'),
    path('topup', show_topup, name='show_topup'),
    path('json-flutter', show_json_flutter, name='show_json_flutter'),
    path('saldo-flutter', edit_saldo_flutter, name='edit_saldo_flutter')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    donatur = 'Donatur'
    fundraiser = 'Fundraiser'
    role_choices = [
        (donatur, 'Donatur'),
        (fundraiser, 'Fundraiser'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='media', default='media/person.png')
    bio = models.TextField(null=True)
    role = models.CharField(choices=role_choices, max_length=10, default=donatur,)
    saldo = models.IntegerField(default=0)
    birthday = models.DateTimeField(null=True)
    email = models.EmailField(null=True)
    phone = models.CharField(max_length=20 ,null=True)

userprofile/forms.py
from django.forms import ModelForm
from.models import UserProfile
from django import forms

class DateInput(forms.DateInput):
    input_type = 'date'

class ProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['picture', 'bio', 'birthday', 'email', 'phone']
        widgets = {
            'birthday' : DateInput(),
        }

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['picture'].required = False
        self.fields['bio'].required = False
        self.fields['birthday'].required = False
        self.fields['email'].required = False
        self.fields['phone'].required = False
        

class TopUpForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['saldo']

    # def clean_saldo(self):
    #     cleaned_data = self.cleaned_data['saldo']
    #     print(cleaned_data)
    #     amount = cleaned_data['saldo']
    #     if amount <= 0:
    #         raise forms.ValidationError("Amount invalid")

    

        

userprofile/views.py
import os
from django.shortcuts import render
from userprofile.models import UserProfile
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.core import serializers
from userprofile.forms import *
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/autentikasi')
def show_profile(request):

    user_data = UserProfile.objects.get(user=request.user)

    bio = user_data.bio
    bday = user_data.birthday
    phone = user_data.phone
    email = user_data.email
    is_donatur = False
    is_fundraiser = False

    if user_data.role == 'Donatur':
        is_donatur = True

    else:
        is_fundraiser = True

    if bio == None:
        bio = "-"

    if bday == None:
        bday = "-"
    
    else:
        bday = bday.strftime("%Y-%m-%d")

    if phone == None:
        phone = "-"

    if email == None:
        email = "-"

    context = {
        'user' : request.user,
        'picture' : user_data.picture,
        'bio' : bio,
        'role' : user_data.role,
        'saldo' : user_data.saldo,
        'birthday' : bday,
        'phone' : phone,
        'email' : email,
        'is_donatur' : is_donatur,
        'is_fundraiser' : is_fundraiser,
        'form1' : ProfileForm,
        'form2' : TopUpForm,
    }
    
    return render(request, 'profile.html', context)

@login_required(login_url='/autentikasi')
def show_topup(request):

    return render(request, 'topup.html')

def edit_profile(request):
    user = request.user.userprofile
    if request.POST:
        form = ProfileForm(request.POST, request.FILES, instance=user)
        print(form.is_valid())

        if form.is_valid():
            obj = form.save(commit=False)

            if obj.picture:
                obj.save(update_fields=['picture'])

            if obj.bio:
                obj.save(update_fields=['bio'])

            if obj.birthday:
                obj.save(update_fields=['birthday'])

            if obj.email:
                obj.save(update_fields=['email'])

            if obj.phone:
                obj.save(update_fields=['phone'])
            

            return HttpResponse("success")

@csrf_exempt
def edit_profile_flutter(request):
    user = request.user.userprofile
    # profileobj = UserProfile.objects.get(user=request.user)
    form = ProfileForm(request.POST, instance=user)
    if request.POST:
        obj = form.save(commit=False)
        print('ini masuk edit profile')
        if obj.picture:
            obj.save(update_fields=['picture'])

        if obj.bio:
            obj.save(update_fields=['bio'])

        if obj.birthday:
            obj.save(update_fields=['birthday'])

        if obj.email:
            obj.save(update_fields=['email'])

        if obj.phone:
            obj.save(update_fields=['phone'])

        # profileobj.save()

        return JsonResponse({"status": "success"}, status=200)

    return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def edit_saldo(request):
    user = request.user.userprofile
    form = TopUpForm(request.POST, instance=user)
    if request.POST:
        obj = form.save(commit=False)

        if obj.saldo:
            obj.save(update_fields=['saldo'])

        # new_saldo = request.POST['saldo']
        # print(f'new saldo {new_saldo}')
        # user_data = UserProfile.objects.get(user=request.user)
        # print(f'user saldo {user_data.saldo}')

        # if int(new_saldo) > 0:
        #     user_data.saldo += int(new_saldo)

        #     user_data.save()
            
        return JsonResponse({"status": "success"}, status=200)

    return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def edit_saldo_flutter(request):
    user = UserProfile.objects.get(user=request.user)
    if request.POST:
        saldo_tambahan = request.POST.get('saldo')
        user.saldo += int(saldo_tambahan)
        user.save()
        
        # if obj.saldo:
        #     obj.save(update_fields=['saldo'])

            
        return JsonResponse({"status": "success"}, status=200)

    return JsonResponse({"status": "error"}, status=401)

def show_json(request):
    profileobj = UserProfile.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", profileobj), content_type="application/json")

def show_json_flutter(request):
    user_data = UserProfile.objects.get(user=request.user)

    return JsonResponse([{"user":str(request.user), "bio":user_data.bio, "role":user_data.role, "saldo":user_data.saldo, "birthday":user_data.birthday, "email":user_data.email, "phone":user_data.phone}], safe=False)

userprofile/templates/profile.html
<!-- Gabisa extends base.html :( -->
{% load static %}


<head>
  <title>{% block title %} {{user}} {% endblock title %}</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
    crossorigin="anonymous"
  />

  <link rel="stylesheet" href="{% static 'css/userprofile.css' %}">
</head>

{% block css %}

{% endblock %}

<header>
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-custom">
    <a class="navbar-brand" href="{% url 'homepage:home' %}">
      <img width="50px" height="50px" src="{%static '/img/logo.png' %}" alt="DONOBOX"> Donobox
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a  href="{% url 'homepage:home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a  href="#about">About Us</a>
        </li>
        <li class="nav-item">
            <a  href="{% url 'artikel:show_artikel' %}">Artikel</a>
        </li>
        <li class="nav-item">
            <a  href="{% url 'crowdfund:show_crowdfunds' %}">Crowdfund</a>
        </li>
        <li class="nav-item">
            <a  href="{% url 'notification:show_notification' %}">Notifikasi</a>
        </li>
        <li class="nav-item">
            <a  href="{% url 'userprofile:show_profile' %}">Profile</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'autentikasi:logout' %}"><button class="submit" type="submit">Logout</button></a>
            </li>
        {% else %}
            <li class="nav-item">
                <a href="{% url 'autentikasi:login' %}"><button class="submit" type="submit">Login</button></a>
            </li>
        {% endif %}
    </ul>
    </div>
  </nav>
</header>

<body style="background-color: rgb(220, 215, 201);">

  {% block content %}
  <section class="section about-section gray-bg" id="about">
    <br>
    <br>
    <div class="container">
      <div class="row align-items-center flex-row-reverse">
        <div class="col-lg-6">
          <div class="about-text go-to">
            <h3 class="dark-color">{{user}}</h3>
            <h6 class="theme-color lead">{{role}}</h6>
            <p id="profilebio"> {{bio}}</p>
            <div class="row about-list">
              <div class="col-md-6">
                <div class="media">
                  <label>Saldo</label>
                  <p>Rp{{saldo}}</p>
                </div>
                <div class="media">
                  <label>Birthday</label>
                  <p id="profilebirthday">{{birthday}}</p>
                </div>
                <div class="media">
                  <a
                    data-bs-toggle="modal"
                    data-bs-target="#modalprofile"
                    class="submit mt-0 ml-1 px-2 p-3"
                    role="button"
                    style = "background-color:  #ffffff; font-family: 'poppins';"
                    
                    >Edit Profile</a
                  >
                  
                </div>
              </div>
              <div class="col-md-6">
                <div class="media">
                  <label>Phone</label>
                  <p id="profilephone">{{phone}}</p>
                </div>
                <div class="media">
                  <label>Email</label>
                  <p id="profileemail">{{email}}</p>
                </div>
                {% if is_donatur %}
                <div class="media">
                  <a href="/profile/topup"><button style="font-family: 'poppins'; background-color: #ffffff;" type="button" class="submit mt-0 ml-1 px-2 p-3">Top Up </button></a>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="about-avatar">
            <img src="{{picture}}" title="" alt="" class="rounded-circle" id="profilepicture"/>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Modal -->
  <div
    class="modal fade"
    id="modalprofile"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Save changes</h1>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <form
            method="POST"
            action="{% url 'userprofile:edit_profile' %}"
            enctype="multipart/form-data"
            id="profileform"
            data-url="{% url 'userprofile:edit_profile' %}"
          >
            {% csrf_token %} 
            <table>
            {{form1.as_table}}
            </table>
            <br />
            <button
              type="button"
              class="btn btn-secondary"
              data-bs-dismiss="modal"
            >
              Close
            </button>
            <button type="submit" id="submitBtn" class="btn btn-primary">
              Save changes
            </button>
          </form>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>

  {% endblock content %}
  <script>
    $(document).ready(function () {
    $("#profileform").on("submit", function (e) {
      e.preventDefault();
      var formData = new FormData(this);

      $.ajax({
        method: "POST",
        url: $("#profileform").data("url"),
        data: formData,
        processData: false,
        contentType: false,

        success: function () {
          alert("Profile succesfully updated");
          $.ajax({
            method: "GET",
            url: "{% url 'userprofile:show_json' %}",

            success: function (response) {
              console.log(response)
              $("#modalprofile").modal('hide');
              $("#profilepicture").attr("src", response[0].fields.picture);
              if (response[0].fields.bio != null){
                $("#profilebio").empty();
                $("#profilebio").html(response[0].fields.bio);
              }

              if (response[0].fields.phone != null){
                $("#profilephone").empty();
              $("#profilephone").html(response[0].fields.phone);
              }

              if (response[0].fields.email != null){
                $("#profileemail").empty();
              $("#profileemail").html(response[0].fields.email);
              }
              
              
              if (response[0].fields.birthday != null){
                $("#profilebirthday").empty();
              $("#profilebirthday").html(response[0].fields.birthday); 
              }
              
            },
          });
        },
      });
    });

  });
  </script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"
  ></script>
</body>

<footer id= "footer" class="footer">
  <div id= "container-footer" class="container">
      <div class="row">
          <div class="footer-col">
              <h4>DONOBOX</h4>
              <ul>
                  <li style="list-style: none;"><a href="homepage/home/#about">About Us</a></li>
                  <li style="list-style: none;"><a href="#ourteam">Our team</a></li>
              </ul>
          </div> 
          <div class="footer-col">
              <h4>CONTACT US</h4>
              <ul>
                  <li style="list-style: none;"><a style="color: #bbbbbb;"><i id class="fa fa-envelope"></i> Donobox@gmail.com</a></li>
                  <li style="list-style: none;"><a style="color: #bbbbbb;" ><i class="fa fa-phone"></i> 021-9272-8161</a></li>
              </ul>
          </div>
          <div class="footer-col">
              <h4>OUR SOCIAL MEDIA</h4>
              <ul>
                  <li style="list-style: none;"><a style="color: #bbbbbb;"><i class="fab fa-facebook"></i> Donobox</a></li>
                  <li style="list-style: none;"><a style="color: #bbbbbb;" ><i class="fab fa-instagram"></i> @donobox_id</a></li>
                  <li style="list-style: none;"><a style="color: #bbbbbb;" ><i class="fab fa-twitter"></i> @donobox_id</a></li>
              </ul>
          </div>
      </div>
  </div>
</footer>